
name: Daily-SIP
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://gentle-dusk-69140.herokuapp.com/' \
          --header 'secret: ${{ secrets.SECRET }}'
